### ISSUE TITLE
Delete Target Bug

### ISSUE THREAD

**Issue by ethmur** [RUAutonomous/ImagingServer#61]
If you try to delete a target that has been submitted to the interop server, while the imaging server is not logged in to the interop server, nothing happens.

Expected behavior: Nothing should actually get deleted. Some sort of error should be alerted or logged to the console.

Actual behavior: Nothing actually gets deleted (which is correct!). No error is alerted or logged.

**Comment by oneTimePad** [comment]
@ethmur  is this fixed?

**Comment by oneTimePad** [comment]
related to #62

**Comment by ethmur** [comment]
Fixed already
